services:
  db:
    image: postgres
    container_name: ${DB_CONTAINER_NAME} # This define the container name
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Password to use
      POSTGRES_USER: ${DB_USER} # User to use
    ports:
      - "${DB_PORT}:5432" # Port to use
    volumes:
      - db_data:/var/lib/mysql # Persist the data
    restart: always # Restart the container if it fails

volumes:
  db_data:
 